winget install -e --id Bitwarden.Bitwarden
winget install -e --id CrystalDewWorld.CrystalDiskMark
winget install -e --id CrystalDewWorld.CrystalDiskInfo
winget install -e --id 7zip.7zip
winget install -e --id ShareX.ShareX
winget install -e --id Audacity.Audacity
winget install -e --id Discord.Discord
winget install -e --id Google.Chrome
winget install -e --id thehandbraketeam.handbrake
winget install -e --id Spotify.Spotify
winget install -e --id Microsoft.RemoteDesktopClient
winget install -e --id OBSProject.OBSStudio
winget install -e --id JAMSoftware.TreeSizeFree
winget install -e --id Telegram.TelegramDesktop
winget install -e --id VideoLAN.VLC
winget install -e --id RevoUninstaller.RevoUninstaller
winget install -e --id Transmission.Transmission
winget install -e --id Duplicati.Duplicati
winget install -e --id voidtools.Everything
winget install -e --id File-New-Project.EarTrumpet
winget install -e --id Rufus.Rufus
